### ISSUE TITLE
Typescript - Provide type declaration for web components

### ISSUE THREAD

**Issue by c-n-d** [AlaskaAirlines/ODS-WC-Generator#10] opened 2019-11-13 18:36 UTC
# Issue report

Consumer of web components who are working with Typescript, will receive an error when attempting to use the component (TS2339).

## Expected Behavior
Orion web components should work without error and should not require additional work to consume by the end user.

## Current Behavior
1. The following error is returned by `tsc`:

```bash
Property 'ods-inputoptions' does not exist on type 'JSX.IntrinsicElements'.ts(2339)
```

## Possible Solution
1. Clients could provide their own type declaration in the short term. This is not sustainable, as every consumer would have to provide type information for each component they use.

```javascript
declare module JSX {
    interface IntrinsicElements {
        'ods-inputoptions': any;
    }
}
```

2. Wrap all web components in JSX components to prevent Typescript from complaining

3. Provide declaration for Orion web components  

## Steps to Reproduce (for bugs)
1. Create a Typescript application with CRA - `create-react-app ts-orion --typescript`
2. Install an Orion component `npm i --save @alaskaairux/ods-button`
3. Use the button in `App.tsx` and find the above error is provide by the compiler

## Context
1. Without type declarations, using Orion components in Typescript projects requires additional, duplicated effort by the developer.

**Comment by blackfalcon** [comment] 2020-02-22 01:45
This is a duplicate issue. Removing the 'bug' tag as this is not a bug with the code, but more so a support request for TypeScript. 

I am closing this issue as the thread has been picked up in the ods-button repo. 
https://github.com/AlaskaAirlines/OrionStatelessComponents__ods-button/issues/50

The proposed solution here has been discussed in the other thread, but it is being decided as to who would be responsible for the work.

**Closed by blackfalcon** 2020-02-22 01:45 UTC
Labels: Priority: Medium, duplicate
